# Generated by Django 4.2.1 on 2023-05-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FootballClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="nazwa")),
                ("founded", models.DateField(verbose_name="data założenia")),
                ("no_players", models.IntegerField(verbose_name="liczba piłkarzy")),
            ],
        ),
        migrations.CreateModel(
            name="FootballPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=256, verbose_name="pierwsze imię"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=256, verbose_name="nazwisko"),
                ),
                ("birth_year", models.IntegerField(verbose_name="rok urodzenia")),
                (
                    "nationality",
                    models.CharField(
                        choices=[("EU", "non EU")],
                        max_length=256,
                        verbose_name="narodowość",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="football_team.footballclub",
                    ),
                ),
            ],
        ),
    ]
