# Generated by Django 4.2.1 on 2023-05-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football_team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footballplayer",
            name="nationality",
            field=models.CharField(
                choices=[("EU", "EU"), ("non EU", "non EU")],
                max_length=256,
                verbose_name="narodowość",
            ),
        ),
    ]
